sudo: required
services:
- docker
language: shell
dist: focal
os: linux
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/amd64 linux/arm64 linux/arm/v7'
  - TAGS='latest'
  - VERSION='0.1'
  - DOCKERFILE='Dockerfile'
  - secure: UrzcAEWO+dQR5AmhX3u/3aCDtqh8QsaQ9vVxo0KelJ3ltc0Ez9foGo16eK27+r70w3ECvuXrk68pflJWtOgjufxLBYAfRNxSZBGd+JWR5huo5FCF7HvGsBk5SBMk6O3thj2XNYDToSy03fpND6K9wgHWx3uPTkqbRYKRbq3Hu6ayq0WUNIbqc7hq6CounsN/7EpeAGXzXCJXzchWPD/GqTOKlKcQI0Yuj+T61saEwvHzswfoLjPLaxN0FL1GQLFulvU6fLgB9C3BYuyVX3pEXCWVoaySm6xHyilIA3X6WIRUMAj+agOpIHDHRfeOLIG/uYqFmJizsd3OczHp29C2vN6C+/kypK/OU6VqfZox9UBqhUdROY+rS4PO2jIBAoN/r8Hb4W4J3OU0uDE5d9AGAEZnr4jhYPWrFLGMD2DO0QsUVgreTsQWYL2Qx4/vAu4gdOd5r/OOoDTCcHbjxN1vNRPR8T8jcXrlseXPeVpzVvYA4vXQdMuf42Y3I6JHOXibu0vozyd5c3xX/ZnJSSFu8VeWJw09Q9VAb7s51yQcfdu4Awg+hnOnfDW5vbBYGXrpabbkT9sllx0t7M14ndcFCQrcjn3IR8swjiKoc6YWlglwDWeCmdnrtzc/guWp7Ji4ctnTEXJapKC3A9xQirMSlDMRRlOapVysaBFZqBjREG8=
  - secure: H+JVCTGCp0SiB9bKLjSyVEGk18Lm/R9IkIfyXTGIzOah0GQV98U0C/0N6HIIY8oLDLTshOKBm03vRJT6P33lqQNn6nFJNP0mUxnnmXhfjYMcZ0ccho7K8q1bmmmK7Ix0o5EKT7V5OPIppB1h6fB4eDi/4A9MLTm8B3pxnZ+d0qRg0uf6GmwNJwRsEbX45VuGhTChJ/EJcdmlu8vUaEdad101j6Hbv15fp3sUu7CO0JpSBvqmTzQEAI+5d+pbtpwl9UWdbmw+qPmnQBmPxqe4loE7uEU8pbHvC0m5/K/bzRDrqv356uJF55CMb0uygy306IKDKcMPy6SgKjBQkMxO1ysQJGjCy7N5fFqDyvhAwu9aDaM32zS/UEFCH+So2gEwQ66MHBlfkIQTdVRTu8NQ3CfonNfpoLkNSvbw//dqTQIyYC9kUEhuacxz9zhYC/3FIy/MmDdy0tWESh3yfhLleMuEs4h2IcBY/Cl4kvb2lOMLzsz68cXp2TNcznYyLKMNMwxXJGzmid7HWbbE2TwkM3nIjsnglQCx+I06rt8I06wBqVZhTCu0nBv/dqH3VGIeLEwKrfLg+i9/YvJm27d11whRHMJK36XBdKkkFW5sYIu3NPzyImXuiQlWK5oreZIokVC+6p+WzJR3iTE/16mBJsUEXaxtY4JMFrjjvDdCAaY=
  - secure: DYDnmK5EAEwkAFOWPJVNz7fS33gr/tYzCVE74nw01628leqi75k8z3SQzuX9N4kpEC+cGnSub4EbPsp7NjBmVRbOJdsy4FmYhauQRAsJY+LbSmM+XTa/VXcoAyGxHX5juBKsxDZgx9dYCxVhwCl3ZwVHsaz8gOUP+jGBP4OCOCGCRwUXE5AyKSCrO6RTQNKfPhh4SCIOLq+heUVa+d6t5YtvAo2PnMkveuM+1sbNfHiaG9jyXpERUQuAMOLA1Wq0nBM6mZWTarZhTmsz7CmAaY1vZE70OhTk5oqfQ5NTC0A5os7j/DGFtF+5e6gQUs5CqjGKMPE+K8qx5uRSnp0GqhQIxLy1wLqYFFDYwYpZipmJb7w2ZwdpjWKQb/Q08dTeNuqArmCOwUiWSTI7L4MAJ37wNcizGjuXi3+Q32ZCaOsorLef9L8fqa+Fl6cE2obacqMwXE9ygoE3lTOiCBpRprM9X+gJ8hTABzA5UpmUvYjDWrvkxuoS1dJbB6PPAW1llNRtj3hXiXfYLLIf4ndRYEVS9WSZziD57t5jJ4W6IcwA6ZpDEpvEvu2ghAAgeY4MIrRHS79ipq/uw6rPGxfAeS4GDajbHHTthuH1pp5Vw88NioL/3UmCsn7ukWAERRaCPpIrK2afRH9t97Ghei0jfJFLlzrqL9mPedvoZ27I1uM=
jobs:
  fast_finish: true
  include:
  - stage: Deploy docker image
    script:
    - source ./buildx_ci_images.sh
    - set -ex; setup_ci_environment::main; set +x
    - set -ex; build_ci_images::main; set +x
